version: "3.9"  # optional since v1.27.0

services:
  db:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    volumes:
      - libdb:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
volumes:
  libdb: {}
